# add a deployment pipeline after the previous ci pipeline to deploy the image to amazon ec2
name: CD

#change on workflow ci run completed
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    # run on different ec2 instance uses IAM authentication the self hosted is running on the aws ec2 instance
    steps:
      - name: Run on Ec2
        run: |
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/platform-tutorial:latest
            sudo docker run -d -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/platform-tutorial:latest

#
#    steps:
#      - name: Run on Ec2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_KEY }}
#          script: |
#            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
#            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/platform-tutorial:latest
#            sudo docker run -d -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/platform-tutorial:latest